apiVersion: v1
kind: Service
metadata:
  name: landing-page
  labels:
    app: landing-page
spec:
  selector:
    app: landing-page
    tier: frontend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000
